language: julia
sudo: false
julia:
    - 0.4
    - 0.5
    - nightly
notifications:
    email: false
#script: # use the default script setting which is equivalent to the following
after_success:
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("Matching")); include(joinpath("docs", "make.jl"))'

